[tool.poetry]
name = "add-user-count"
version = "0.1.0"
description = ""
authors = ["seano"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
argparse = "^1.4.0"
requests = "^2.32.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
